image: Visual Studio 2015

environment:
  ARCH: x86
    
clone_depth: 1

platform:
  - x64
  
environment:
  sf_secret:
    secure: 8QOHSPQLI/lmjgOhyGOsMA5MxOdeSnlFWWKjntqEfBMfW/XCuiEk5tHNjZiiAw8N
  sf_api:
    secure: S4qrbAdLq3Hw5yozC7XAavTGzpPPh8MleX+r8kaueBtPZUeJGt+8EoqaPw0P1PzV
  
init:
  - if /i %APPVEYOR_REPO_TAG% == true    set WITH_TESSDATA=1

cache:
  - installed -> scripts\win\prepare.bat

install:
  - cinst winscp
  - nuget install secure-file -ExcludeVersion
  - call "scripts\win\prepare.bat"

build_script:
  - call "scripts\win\build.bat"

artifacts:
  - path: 'screen-translator-*.exe'
    name: installer

deploy:
  - provider: GitHub
    description: "Version $(APPVEYOR_REPO_TAG_NAME)"
    auth_token:
      secure: NnyUV44yNAx8ea1L46dVhE4kQxUGd5M1O+yVk+9ncsNHWtw/9JoCnDqNybnxTccP
    artifact: installer
    force_update: true
    on:
      appveyor_repo_tag: true

after_deploy:
  - secure-file\tools\secure-file -decrypt scripts\win\sf_key.av -secret %sf_secret% -out scripts\win\sf_key
  - call "scripts\win\deploy_sf.bat"
