image: Visual Studio 2015

environment:
  ARCH: x86
    
clone_depth: 1

platform:
  - x64
  
init:
  - if /i %APPVEYOR_REPO_TAG% == true    set WITH_TESSDATA=1
  
install:
  - call "scripts\win\prepare.bat"

build_script:
  - call "scripts\win\build.bat"

artifacts:
  - path: 'screen-translator-*.exe'
    name: installer

deploy:
  - provider: GitHub
    description: "Version $(APPVEYOR_REPO_TAG_NAME)"
    auth_token:
      secure: NnyUV44yNAx8ea1L46dVhE4kQxUGd5M1O+yVk+9ncsNHWtw/9JoCnDqNybnxTccP
    artifact: installer
    force_update: true
    on:
      appveyor_repo_tag: true
